import { useEffect, useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, RefreshCcw, ShieldCheck, Store, XCircle } from "lucide-react";
import { loadSessionProfile, supabase } from "../lib/roles";

type Application={id:string;business_name:string;neighborhood:string;kind:string;owner_name:string|null;phone:string|null;email:string|null;desired_plan:string;status:string;created_at:string;merchant_id:string|null};
type Merchant={id:string;name:string;status:string;plan_code:string;phone:string|null;email:string|null;created_at:string;merchant_members?:Array<{count:number}>};
const dt=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"});

export function AdminMerchantManagement(){
 const [authorized,setAuthorized]=useState<boolean|null>(null),[applications,setApplications]=useState<Application[]>([]),[merchants,setMerchants]=useState<Merchant[]>([]),[busy,setBusy]=useState(""),[notice,setNotice]=useState(""),[ownerIdentifiers,setOwnerIdentifiers]=useState<Record<string,string>>({}),[ownerPins,setOwnerPins]=useState<Record<string,string>>({});
 async function load(){if(!supabase)return;const [{data:a},{data:m}]=await Promise.all([supabase.from("merchant_applications").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("merchants").select("id,name,status,plan_code,phone,email,created_at,merchant_members(count)").order("created_at",{ascending:false}).limit(200)]);setApplications((a??[]) as Application[]);setMerchants((m??[]) as Merchant[])}
 useEffect(()=>{void(async()=>{const p=await loadSessionProfile();setAuthorized(Boolean(p?.isAdmin));if(p?.isAdmin)await load()})()},[]);
 async function review(id:string,decision:"approved"|"rejected"){if(!supabase)return;setBusy(id);const notes=decision==="rejected"?window.prompt("Motivo da rejeição (opcional):")||null:null;const {error}=await supabase.rpc("review_merchant_application",{_application_id:id,_decision:decision,_admin_notes:notes});setBusy("");setNotice(error?error.message:decision==="approved"?"Estabelecimento aprovado e painel vinculado ao responsável.":"Solicitação rejeitada.");await load()}
 async function updateMerchant(id:string,values:Partial<Pick<Merchant,"status"|"plan_code">>){if(!supabase)return;setBusy(id);const {error}=await supabase.from("merchants").update({...values,updated_at:new Date().toISOString()}).eq("id",id);setBusy("");setNotice(error?error.message:"Cadastro atualizado.");await load()}
 async function activateOwner(merchant:Merchant){if(!supabase)return;const identifier=(ownerIdentifiers[merchant.id]||merchant.email||"").trim(),cpf=identifier.replace(/\D/g,"");const cpfMode=cpf.length===11,pin=(ownerPins[merchant.id]||"").replace(/\D/g,"");if(!identifier){setNotice("Informe o e-mail ou CPF do responsável.");return}if(cpfMode&&pin.length!==6){setNotice("Para acesso por CPF, defina um novo PIN de 6 dígitos.");return}setBusy(merchant.id);const {data,error}=await supabase.functions.invoke("admin-merchant-owner",{body:{merchantId:merchant.id,...(cpfMode?{cpf,pin}:{email:identifier})}});let detail=data?.error||error?.message;if(error&&"context" in error){try{const payload=await (error as any).context.json();detail=payload?.error||detail}catch{/* resposta sem JSON */}}setBusy("");setNotice(detail||(data?.invited?"Convite enviado e acesso ao painel preparado.":"Responsável vinculado e acesso ao painel ativado."));await load()}
 if(authorized===null)return <main style={s.center}><RefreshCcw/> Verificando acesso…</main>; if(!authorized)return <main style={s.center}><ShieldCheck size={42}/><h1>Acesso restrito</h1><a href="/">Voltar</a></main>;
 const pending=applications.filter(a=>a.status==="pending");
 return <main style={s.page}><header style={s.header}><a href="/admin/plataforma" style={s.back}><ArrowLeft size={16}/> Painel da plataforma</a><button style={s.secondary} onClick={()=>void load()}><RefreshCcw size={15}/> Atualizar</button></header><section style={s.hero}><span style={s.kicker}>ADMINISTRAÇÃO · ESTABELECIMENTOS</span><h1 style={s.h1}>Comércios e planos</h1><p>Você aprova cadastros e controla situação e plano. Pedidos, estoque, equipe e caixa do lojista não aparecem aqui.</p></section>{notice&&<div style={s.notice}>{notice}</div>}
 <section style={s.section}><div style={s.sectionHead}><div><span style={s.kicker}>SOLICITAÇÕES</span><h2>Pendentes de aprovação</h2></div><b>{pending.length}</b></div><div style={s.grid}>{pending.map(a=><article key={a.id} style={s.card}><div style={s.cardTop}><div style={s.icon}><Building2 size={19}/></div><small>{dt.format(new Date(a.created_at))}</small></div><h3>{a.business_name}</h3><p>{a.neighborhood} · {a.kind}</p><div style={s.meta}><span>Responsável <b>{a.owner_name||"—"}</b></span><span>Contato <b>{a.phone||a.email||"—"}</b></span><span>Plano <b>{a.desired_plan}</b></span></div><div style={s.actions}><button disabled={busy===a.id} onClick={()=>void review(a.id,"approved")} style={s.approve}><CheckCircle2 size={15}/> Aprovar</button><button disabled={busy===a.id} onClick={()=>void review(a.id,"rejected")} style={s.reject}><XCircle size={15}/> Rejeitar</button></div></article>)}{!pending.length&&<div style={s.empty}>Nenhuma solicitação pendente.</div>}</div></section>
 <section style={s.section}><div style={s.sectionHead}><div><span style={s.kicker}>ESTABELECIMENTOS</span><h2>Lojas cadastradas</h2></div><b>{merchants.length}</b></div><div style={s.table}>{merchants.map(m=>{const owners=m.merchant_members?.[0]?.count??0,identifier=ownerIdentifiers[m.id]??m.email??"",cpfMode=identifier.replace(/\D/g,"").length===11;return <div key={m.id} style={s.row}><div style={s.store}><Store size={17}/><span><strong>{m.name}</strong><small>{owners?`${owners} responsável(is) com acesso`:`SEM RESPONSÁVEL VINCULADO · ${m.email||m.phone||"sem contato"}`}</small></span></div><select value={m.plan_code} onChange={e=>void updateMerchant(m.id,{plan_code:e.target.value})} disabled={busy===m.id} style={s.select}><option value="essential">Essencial</option><option value="professional">Profissional</option><option value="premium">Premium</option></select><select value={m.status} onChange={e=>void updateMerchant(m.id,{status:e.target.value})} disabled={busy===m.id} style={s.select}><option value="pending">Pendente</option><option value="active">Ativo</option><option value="suspended">Suspenso</option><option value="blocked">Bloqueado</option></select><div style={s.ownerAction}><input value={identifier} onChange={e=>setOwnerIdentifiers(v=>({...v,[m.id]:e.target.value}))} placeholder="E-mail ou CPF" style={s.input}/>{cpfMode&&<input value={ownerPins[m.id]??""} onChange={e=>setOwnerPins(v=>({...v,[m.id]:e.target.value.replace(/\D/g,"").slice(0,6)}))} placeholder="Novo PIN" inputMode="numeric" type="password" style={{...s.input,maxWidth:95}}/>}<button onClick={()=>void activateOwner(m)} disabled={busy===m.id} style={s.activate}>{owners?"Vincular outro":"Ativar acesso"}</button></div></div>})}</div></section></main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f5f7f6",padding:"24px clamp(16px,4vw,60px) 70px",fontFamily:"Inter,system-ui,sans-serif",color:"#152019"},header:{maxWidth:1250,margin:"0 auto",display:"flex",justifyContent:"space-between"},back:{display:"flex",gap:6,alignItems:"center",color:"inherit",textDecoration:"none",fontWeight:750},secondary:{border:"1px solid #dce3de",background:"white",borderRadius:10,padding:"9px 12px",display:"flex",gap:6,alignItems:"center",cursor:"pointer"},hero:{maxWidth:1250,margin:"38px auto 18px"},kicker:{fontSize:10,fontWeight:900,letterSpacing:".13em",opacity:.55},h1:{fontSize:42,letterSpacing:"-.05em",margin:"6px 0"},notice:{maxWidth:1250,margin:"0 auto 12px",padding:12,borderRadius:11,background:"#eaf5ee",color:"#195d38"},section:{maxWidth:1250,margin:"12px auto 0",background:"white",border:"1px solid #e0e5e2",borderRadius:17,padding:20},sectionHead:{display:"flex",justifyContent:"space-between",alignItems:"center"},grid:{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:10},card:{border:"1px solid #e5e9e6",borderRadius:14,padding:16},cardTop:{display:"flex",justifyContent:"space-between",alignItems:"center"},icon:{width:36,height:36,borderRadius:10,display:"grid",placeItems:"center",background:"#edf4ef"},meta:{display:"grid",gap:5,fontSize:12,color:"#667269"},actions:{display:"flex",gap:7,marginTop:14},approve:{flex:1,border:0,borderRadius:9,padding:9,background:"#183d2b",color:"white",fontWeight:800,display:"flex",justifyContent:"center",gap:5,cursor:"pointer"},reject:{border:"1px solid #e4caca",borderRadius:9,padding:9,background:"#fff8f8",color:"#9a3333",fontWeight:800,display:"flex",gap:5,cursor:"pointer"},table:{display:"grid",gap:7},row:{display:"grid",gridTemplateColumns:"minmax(240px,1fr) 150px 140px minmax(270px,1fr)",gap:10,alignItems:"center",padding:11,border:"1px solid #edf0ee",borderRadius:11},store:{display:"flex",gap:9,alignItems:"center"},select:{minHeight:38,border:"1px solid #dce3de",borderRadius:9,padding:"0 8px",background:"white"},ownerAction:{display:"flex",gap:6},input:{minWidth:0,flex:1,minHeight:38,border:"1px solid #dce3de",borderRadius:9,padding:"0 9px"},activate:{border:0,borderRadius:9,padding:"0 11px",background:"#183d2b",color:"white",fontWeight:800,cursor:"pointer"},empty:{padding:30,textAlign:"center",color:"#778078"},center:{minHeight:"100vh",display:"grid",placeItems:"center",fontFamily:"Inter,system-ui,sans-serif"}}
