import { FormEvent, useEffect, useMemo, useState } from "react";
import { BookOpen, Check, Copy, CreditCard, ExternalLink, QrCode, X } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "../lib/supabase";

type Book={id:string;slug:string;name:string;price:number;promotional_price:number|null;price_on_request:boolean;preview_url?:string|null;preview_summary?:string|null;external_url?:string|null};
type Profile={merchant:{guest_pix_enabled?:boolean};books:Book[]};
type PixResult={orderNumber:string;status:string;qrCode?:string|null;qrCodeBase64?:string|null;ticketUrl?:string|null;total:number};
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const authorPaths=new Set(["/autora/dorinha-barroso","/dorinha-barroso"]);
function qrUrl(slug:string){const base=String(import.meta.env.VITE_SUPABASE_URL||"").replace(/\/$/,"");return `${base}/functions/v1/book-sales-qr?book=${encodeURIComponent(slug)}`}

export function DorinhaCommerceEnhancer(){
 const location=useLocation();
 const active=authorPaths.has(location.pathname);
 const [profile,setProfile]=useState<Profile|null>(null),[book,setBook]=useState<Book|null>(null),[pix,setPix]=useState<PixResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(false),[showQr,setShowQr]=useState(false);
 useEffect(()=>{if(!active||!supabase)return;void supabase.rpc("author_store_public_profile",{_slug:"dorinha-barroso-livros"}).then(({data})=>setProfile(data as Profile));},[active]);
 useEffect(()=>{if(!active||!profile)return;const wanted=new URLSearchParams(location.search).get("comprar");if(wanted){const b=profile.books.find(x=>x.slug===wanted);if(b)setBook(b)}},[active,profile,location.search]);
 useEffect(()=>{if(!active||!profile)return;const enhance=()=>{document.querySelectorAll("article").forEach(card=>{const title=Array.from(card.querySelectorAll("h3,strong")).map(x=>x.textContent?.trim()).find(t=>profile.books.some(b=>b.name===t));if(!title)return;const b=profile.books.find(x=>x.name===title);if(!b)return;const direct=Array.from(card.querySelectorAll("a")).find(a=>a.textContent?.includes("Comprar direto"));if(direct&&!direct.getAttribute("data-pc-pix")){direct.setAttribute("data-pc-pix",b.slug);direct.setAttribute("href",`?comprar=${encodeURIComponent(b.slug)}`);direct.innerHTML="Comprar com PIX";direct.addEventListener("click",e=>{e.preventDefault();setBook(b);history.replaceState(null,"",`${location.pathname}?comprar=${encodeURIComponent(b.slug)}`)});const row=document.createElement("div");row.setAttribute("data-pc-book-tools",b.slug);row.style.cssText="display:flex;gap:6px;margin-top:8px";if(b.preview_url){const a=document.createElement("a");a.href=b.preview_url;a.target="_blank";a.rel="noreferrer";a.textContent="Ler prévia";a.style.cssText="flex:1;text-align:center;padding:9px;border:1px solid #ded6df;border-radius:9px;text-decoration:none;color:#493c4e;font-size:11px;font-weight:800";row.appendChild(a)}const q=document.createElement("button");q.type="button";q.textContent="QR da obra";q.style.cssText="flex:1;padding:9px;border:1px solid #ded6df;border-radius:9px;background:#fff;color:#493c4e;font-size:11px;font-weight:800;cursor:pointer";q.onclick=()=>{setBook(b);setShowQr(true)};row.appendChild(q);direct.parentElement?.parentElement?.appendChild(row)}})};enhance();const mo=new MutationObserver(enhance);mo.observe(document.body,{subtree:true,childList:true});return()=>mo.disconnect()},[active,profile,location.pathname]);
 const unit=useMemo(()=>book?Number(book.promotional_price??book.price??0):0,[book]);
 function close(){setBook(null);setPix(null);setError("");setShowQr(false);if(active)history.replaceState(null,"",location.pathname)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!book||!supabase)return;setBusy(true);setError("");setPix(null);const fd=new FormData(e.currentTarget);const {data,error:fnError}=await supabase.functions.invoke("author-guest-pix",{body:{bookId:book.id,quantity:Number(fd.get("quantity")||1),name:String(fd.get("name")||""),email:String(fd.get("email")||""),cpf:String(fd.get("cpf")||""),phone:String(fd.get("phone")||"")}});setBusy(false);if(fnError||data?.error){setError(data?.error||fnError?.message||"Não foi possível gerar o PIX.");return}setPix(data as PixResult)}
 async function copyPix(){if(!pix?.qrCode)return;await navigator.clipboard.writeText(pix.qrCode);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 if(!active||!book)return null;
 return <div style={s.overlay} role="dialog" aria-modal="true"><div style={s.modal}><button style={s.close} onClick={close}><X/></button><div style={s.head}><span style={s.kicker}>COMPRA SEM CADASTRO · PIX</span><h2>{book.name}</h2><p>Informe os dados da compra. Você não precisa criar conta no PreçoCerto. O pedido só é marcado como pago após a confirmação do Mercado Pago.</p></div>{showQr&&!pix?<section style={s.qrSection}><QrCode size={22}/><h3>QR da obra</h3><p>Use este QR em material impresso para levar o leitor diretamente à compra deste título.</p><img src={qrUrl(book.slug)} alt={`QR para comprar ${book.name}`} style={s.bookQr}/><button style={s.secondary} onClick={()=>setShowQr(false)}>Ir para pagamento PIX</button></section>:pix?<section style={s.pix}><span style={s.ok}><Check/> PIX gerado</span><h3>Pedido #{pix.orderNumber}</h3><strong style={s.total}>{brl.format(pix.total)}</strong>{pix.qrCodeBase64&&<img src={`data:image/png;base64,${pix.qrCodeBase64}`} alt="QR Code PIX" style={s.pixQr}/>}<button onClick={copyPix} style={s.primary}><Copy size={17}/>{copied?"Código copiado":"Copiar código PIX"}</button>{pix.ticketUrl&&<a href={pix.ticketUrl} target="_blank" rel="noreferrer" style={s.secondary}><ExternalLink size={16}/> Abrir página do PIX</a>}<p style={s.helper}>Quando o Mercado Pago confirmar o pagamento, o pedido será liberado automaticamente e o e-mail de confirmação será enviado ao endereço informado.</p></section>:<form onSubmit={submit} style={s.form}>{unit>0?<div style={s.price}><span>Preço atual</span><strong>{brl.format(unit)}</strong></div>:<div style={s.warning}>O preço deste título ainda não foi sincronizado. O PIX será liberado assim que a autora definir o valor no painel.</div>}{book.preview_url&&<a href={book.preview_url} target="_blank" rel="noreferrer" style={s.preview}><BookOpen size={16}/> Ler uma prévia antes de comprar</a>}<label>Nome completo<input name="name" required autoComplete="name"/></label><label>E-mail para confirmação<input name="email" type="email" required autoComplete="email"/></label><div style={s.two}><label>CPF<input name="cpf" inputMode="numeric" required maxLength={14}/></label><label>Telefone<input name="phone" inputMode="tel" autoComplete="tel"/></label></div><label>Quantidade<input name="quantity" type="number" min="1" max="10" defaultValue="1" required/></label>{error&&<div style={s.error}>{error}</div>}<button disabled={busy||unit<=0} style={s.primary}><CreditCard size={17}/>{busy?"Gerando PIX…":"Gerar PIX e QR Code"}</button><button type="button" onClick={()=>setShowQr(true)} style={s.secondary}><QrCode size={16}/> Ver QR da obra</button><small style={s.helper}>O CPF é enviado ao Mercado Pago para processar o PIX. O PreçoCerto guarda apenas dados mínimos de rastreio do pedido.</small></form>}</div></div>
}
const s:Record<string,React.CSSProperties>={overlay:{position:"fixed",inset:0,zIndex:9999,background:"rgba(14,9,19,.72)",backdropFilter:"blur(8px)",display:"grid",placeItems:"center",padding:16},modal:{width:"min(560px,100%)",maxHeight:"92vh",overflow:"auto",background:"#fff",borderRadius:22,padding:"28px",position:"relative",boxShadow:"0 35px 90px rgba(0,0,0,.32)",fontFamily:"Inter,system-ui,sans-serif"},close:{position:"absolute",right:14,top:14,border:0,background:"#f1edf2",borderRadius:10,width:38,height:38,display:"grid",placeItems:"center",cursor:"pointer"},head:{paddingRight:40},kicker:{fontSize:10,fontWeight:900,letterSpacing:".13em",color:"#75507e"},form:{display:"grid",gap:12,marginTop:20},two:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10},price:{display:"flex",justifyContent:"space-between",alignItems:"center",padding:14,borderRadius:12,background:"#f5f0f6"},warning:{padding:12,borderRadius:10,background:"#fff5df",color:"#795515",fontSize:12},preview:{display:"flex",alignItems:"center",gap:7,padding:11,borderRadius:10,border:"1px solid #ded5df",textDecoration:"none",color:"#493b4e",fontWeight:800,fontSize:12},primary:{minHeight:48,border:0,borderRadius:11,background:"#34203f",color:"#fff",display:"flex",alignItems:"center",justifyContent:"center",gap:8,fontWeight:900,cursor:"pointer",textDecoration:"none"},secondary:{minHeight:44,border:"1px solid #ddd5df",borderRadius:11,background:"#fff",color:"#45384b",display:"flex",alignItems:"center",justifyContent:"center",gap:8,fontWeight:800,cursor:"pointer",textDecoration:"none"},error:{padding:11,borderRadius:10,background:"#fff0f0",color:"#9a3030",fontSize:12},helper:{color:"#7c727f",fontSize:10,lineHeight:1.5},pix:{display:"grid",gap:12,textAlign:"center",marginTop:18},ok:{display:"inline-flex",margin:"0 auto",gap:6,alignItems:"center",color:"#237147",fontWeight:900},total:{fontSize:28},pixQr:{width:240,height:240,objectFit:"contain",margin:"0 auto"},qrSection:{display:"grid",placeItems:"center",textAlign:"center",gap:10,marginTop:20},bookQr:{width:220,height:220,background:"white",border:"1px solid #eee",borderRadius:14,padding:8}};