import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { BadgeCheck, ChevronRight, Music2, Play, Sparkles, Video } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "../lib/supabase";

type Item={display_name:string;slug:string;tagline:string|null;youtube_url:string|null;verified:boolean;accent_color:string|null};
export function LocalCultureSpotlight(){
 const location=useLocation();const[host,setHost]=useState<HTMLElement|null>(null),[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{if(location.pathname!=="/"){setHost(null);return}let own:HTMLElement|null=null;const mount=()=>{const main=document.querySelector("main");if(!main)return false;const old=document.getElementById("pc-local-culture");if(old){setHost(old);return true}own=document.createElement("div");own.id="pc-local-culture";const premium=document.getElementById("pc-premium-home");if(premium)premium.after(own);else main.appendChild(own);setHost(own);return true};if(!mount()){const mo=new MutationObserver(()=>{if(mount())mo.disconnect()});mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()}return()=>own?.remove()},[location.pathname]);
 useEffect(()=>{if(location.pathname!=="/"||!supabase)return;void(async()=>{const{data}=await supabase.from("cultural_profiles").select("display_name,slug,tagline,youtube_url,verified,accent_color").eq("featured",true).limit(4);setItems((data??[]) as Item[])})()},[location.pathname]);
 if(!host||!items.length)return null;
 return createPortal(<section style={s.wrap}><div style={s.shell}><div style={s.copy}><span style={s.kicker}><Sparkles size={13}/> CULTURA & CRIADORES LOCAIS</span><h2 style={s.h2}>A cidade também tem som, histórias e gente criando.</h2><p style={s.text}>Um espaço editorial para descobrir projetos locais sem transformar a Home em um portal de entretenimento. O comércio continua no centro; a cultura entra como uma vitrine complementar.</p></div><div style={s.grid}>{items.map(x=><article key={x.slug} style={{...s.card,borderColor:x.accent_color?`${x.accent_color}55`:undefined}}><div style={{...s.icon,background:x.accent_color||"#7c3aed"}}><Music2/></div><div style={s.badges}>{x.verified&&<span style={s.verified}><BadgeCheck size={12}/> Verificado</span>}<span style={s.type}>Música local</span></div><h3 style={s.title}>{x.display_name}</h3><p style={s.desc}>{x.tagline}</p><div style={s.actions}><a href={`/cultura/${x.slug}`} style={s.primary}><Play size={15}/> Conhecer projeto</a>{x.youtube_url&&<a href={x.youtube_url} target="_blank" rel="noreferrer" style={s.youtube}><Video size={15}/></a>}</div></article>)}</div><div style={s.footer}><span>Produz cultura local? O PreçoCerto pode criar um espaço editorial verificado para o seu projeto.</span><a href="/fale-conosco">Falar com o PreçoCerto <ChevronRight size={15}/></a></div></div></section>,host);
}
const s:Record<string,React.CSSProperties>={wrap:{maxWidth:1240,margin:"0 auto",padding:"18px 24px 64px",fontFamily:"Inter,system-ui,sans-serif"},shell:{borderRadius:22,padding:"clamp(20px,3vw,34px)",background:"linear-gradient(135deg,#17101f,#291438 70%,#3f1a47)",color:"white",boxShadow:"0 20px 60px rgba(45,23,57,.14)"},copy:{maxWidth:790},kicker:{display:"inline-flex",gap:6,alignItems:"center",fontSize:10,fontWeight:950,letterSpacing:".14em",color:"#e9c9ff"},h2:{fontFamily:"Georgia,serif",fontSize:"clamp(2rem,4vw,3.5rem)",lineHeight:1.04,letterSpacing:"-.04em",margin:"9px 0 12px"},text:{color:"#c2b6c9",fontSize:13,lineHeight:1.7},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12,marginTop:23},card:{border:"1px solid rgba(255,255,255,.12)",borderRadius:16,padding:17,background:"rgba(255,255,255,.055)",display:"flex",flexDirection:"column",gap:9},icon:{width:46,height:46,borderRadius:13,display:"grid",placeItems:"center",color:"white"},badges:{display:"flex",gap:6,flexWrap:"wrap"},verified:{display:"inline-flex",alignItems:"center",gap:4,fontSize:9,fontWeight:900,background:"rgba(147,197,253,.12)",color:"#cce7ff",padding:"5px 7px",borderRadius:999},type:{fontSize:9,fontWeight:900,color:"#d9bfdc",padding:"5px 0"},title:{fontSize:21,margin:"2px 0"},desc:{fontSize:12,lineHeight:1.55,color:"#c7bbc9",minHeight:56},actions:{display:"grid",gridTemplateColumns:"1fr 42px",gap:7,marginTop:"auto"},primary:{display:"flex",alignItems:"center",justifyContent:"center",gap:6,minHeight:42,borderRadius:10,background:"white",color:"#25152e",textDecoration:"none",fontWeight:850,fontSize:12},youtube:{display:"grid",placeItems:"center",borderRadius:10,background:"#ff0033",color:"white",textDecoration:"none"},footer:{display:"flex",justifyContent:"space-between",gap:18,alignItems:"center",marginTop:18,paddingTop:16,borderTop:"1px solid rgba(255,255,255,.09)",fontSize:11,color:"#ad9fb2"}};