import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { BadgeCheck, ChevronRight, Music2, Play, Sparkles, Video } from "lucide-react";
import { useLocation } from "react-router-dom";
import { supabase } from "../lib/supabase";

type Item={display_name:string;slug:string;tagline:string|null;youtube_url:string|null;verified:boolean;accent_color:string|null};
export function LocalCultureSpotlight(){
 const location=useLocation();const[host,setHost]=useState<HTMLElement|null>(null),[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{if(location.pathname!=="/"){setHost(null);return}let own:HTMLElement|null=null;const mount=()=>{const main=document.querySelector("main");if(!main)return false;const old=document.getElementById("pc-local-culture");if(old){setHost(old);return true}own=document.createElement("div");own.id="pc-local-culture";const premium=document.getElementById("pc-premium-home");if(premium)premium.after(own);else main.appendChild(own);setHost(own);return true};if(!mount()){const mo=new MutationObserver(()=>{if(mount())mo.disconnect()});mo.observe(document.body,{childList:true,subtree:true});return()=>mo.disconnect()}return()=>own?.remove()},[location.pathname]);
 useEffect(()=>{if(location.pathname!=="/"||!supabase)return;void(async()=>{const{data}=await supabase.from("cultural_profiles").select("display_name,slug,tagline,youtube_url,verified,accent_color").eq("featured",true).limit(4);setItems((data??[]) as Item[])})()},[location.pathname]);
 if(!host||!items.length)return null;
 return createPortal(<section style={s.wrap}><div style={s.shell}><div style={s.copy}><span style={s.kicker}><Sparkles size={13}/> CULTURA & CRIADORES LOCAIS</span><h2 style={s.h2}>A cidade também tem som, histórias e gente criando.</h2><p style={s.text}>Um espaço editorial para descobrir projetos locais sem transformar a Home em um portal de entretenimento. O comércio continua no centro; a cultura entra como uma vitrine complementar.</p></div><div style={s.grid}>{items.map(x=><article key={x.slug} style={{...s.card,borderColor:x.accent_color?`${x.accent_color}55`:undefined}}><div style={{...s.icon,background:x.accent_color||"#7c3aed"}}><Music2/></div><div style={s.badges}>{x.verified&&<span style={s.verified}><BadgeCheck size={12}/> Verificado</span>}<span style={s.type}>Música local</span></div><h3 style={s.title}>{x.display_name}</h3><p style={s.desc}>{x.tagline}</p><div style={s.actions}><a href={`/cultura/${x.slug}`} style={s.primary}><Play size={15}/> Conhecer projeto</a>{x.youtube_url&&<a href={x.youtube_url} target="_blank" rel="noreferrer" style={s.youtube}><Video size={15}/></a>}</div></article>)}</div><div style={s.footer}><span>Produz cultura local? O PreçoCerto pode criar um espaço editorial verificado para o seu projeto.</span><a href="/fale-conosco">Falar com o PreçoCerto <ChevronRight size={15}/></a></div></div></section>,host);
}
const s:Record<string,React.CSSProperties>={wrap:{maxWidth:1240,margin:"0 auto",padding:"14px 24px 50px",fontFamily:"Inter,system-ui,sans-serif"},shell:{borderRadius:20,padding:"clamp(18px,2.5vw,28px)",background:"linear-gradient(135deg,#17101f,#291438 70%,#3f1a47)",color:"white",boxShadow:"0 15px 45px rgba(45,23,57,.12)"},copy:{maxWidth:700},kicker:{display:"inline-flex",gap:6,alignItems:"center",fontSize:9,fontWeight:950,letterSpacing:".14em",color:"#e9c9ff"},h2:{fontFamily:"Georgia,serif",fontSize:"clamp(1.6rem,3.2vw,2.4rem)",lineHeight:1.06,letterSpacing:"-.04em",margin:"7px 0 9px"},text:{color:"#c2b6c9",fontSize:12,lineHeight:1.6,opacity:0.9},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,marginTop:20},card:{border:"1px solid rgba(255,255,255,.12)",borderRadius:14,padding:14,background:"rgba(255,255,255,.055)",display:"flex",flexDirection:"column",gap:7},icon:{width:38,height:38,borderRadius:10,display:"grid",placeItems:"center",color:"white",transform:"scale(0.9)"},badges:{display:"flex",gap:5,flexWrap:"wrap"},verified:{display:"inline-flex",alignItems:"center",gap:3,fontSize:8.5,fontWeight:900,background:"rgba(147,197,253,.12)",color:"#cce7ff",padding:"4px 6px",borderRadius:999},type:{fontSize:8.5,fontWeight:900,color:"#d9bfdc",padding:"4px 0"},title:{fontSize:17,fontWeight:800,margin:"1px 0",letterSpacing:"-0.01em"},desc:{fontSize:11,lineHeight:1.45,color:"#c7bbc9",minHeight:42,overflow:"hidden",display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical"},actions:{display:"grid",gridTemplateColumns:"1fr 36px",gap:6,marginTop:"auto"},primary:{display:"flex",alignItems:"center",justifyContent:"center",gap:5,minHeight:36,borderRadius:8,background:"white",color:"#25152e",textDecoration:"none",fontWeight:850,fontSize:11},youtube:{display:"grid",placeItems:"center",borderRadius:8,background:"#ff0033",color:"white",textDecoration:"none"},footer:{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",marginTop:16,paddingTop:14,borderTop:"1px solid rgba(255,255,255,.09)",fontSize:10,color:"#ad9fb2"}};