import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, CreditCard, LockKeyhole, Minus, Moon, Plus, QrCode, ShieldCheck, ShoppingBag, Store, Sun, Truck } from "lucide-react";
import { useParams } from "react-router-dom";
import { completeDemoPayment, createMarketplaceOrder, loadDeliveryZones, startMercadoPagoCheckout, type DeliveryZone, type MerchantProduct } from "../lib/merchantPlatform";
import { supabase } from "../lib/roles";
import "./MerchantStorefrontProMax.css";

const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
type Merchant={id:string;name:string;phone:string|null;address:any;delivery_enabled:boolean;pickup_enabled:boolean;min_order:number;opening_hours:any;status:string;service_settings?:{demo_mode?:boolean;allow_demo_payment?:boolean}};
type Cart=Record<string,number>;
type Theme="light"|"dark";
const readTheme=():Theme=>{if(typeof window==="undefined")return"light";const saved=window.localStorage.getItem("precocerto-theme");if(saved==="dark"||saved==="light")return saved;return window.matchMedia?.("(prefers-color-scheme: dark)").matches?"dark":"light"};

export function MerchantStorefront(){
 const {merchantId=""}=useParams();
 const [merchant,setMerchant]=useState<Merchant|null>(null),[products,setProducts]=useState<MerchantProduct[]>([]),[zones,setZones]=useState<DeliveryZone[]>([]),[cart,setCart]=useState<Cart>({}),[deliveryType,setDeliveryType]=useState<"delivery"|"pickup">("delivery"),[zoneId,setZoneId]=useState(""),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[notice,setNotice]=useState(""),[theme,setTheme]=useState<Theme>(readTheme);
 useEffect(()=>{document.documentElement.dataset.theme=theme;window.localStorage.setItem("precocerto-theme",theme)},[theme]);
 useEffect(()=>{void(async()=>{if(!supabase||!merchantId){setLoading(false);return}const [{data:m},{data:p},{data:s},z]=await Promise.all([supabase.from("merchants").select("id,name,phone,address,delivery_enabled,pickup_enabled,min_order,opening_hours,status,service_settings").eq("id",merchantId).eq("status","active").eq("online_sales_enabled",true).maybeSingle(),supabase.from("merchant_products").select("*").eq("merchant_id",merchantId).eq("active",true).eq("available",true).order("product_name"),supabase.auth.getSession(),loadDeliveryZones(merchantId)]);setMerchant(m as Merchant|null);setProducts((p??[]).map((r:any)=>({...r,price:Number(r.price||0),promotional_price:r.promotional_price==null?null:Number(r.promotional_price),stock_quantity:Number(r.stock_quantity||0)})) as MerchantProduct[]);setZones(z.filter(x=>x.active));setUser(s.session?.user??null);if(m&&!m.delivery_enabled&&m.pickup_enabled)setDeliveryType("pickup");setLoading(false)})()},[merchantId]);
 const chosen=useMemo(()=>products.filter(p=>cart[p.id]>0).map(p=>({...p,qty:cart[p.id]})),[products,cart]);
 const subtotal=useMemo(()=>chosen.reduce((sum,p)=>sum+(p.promotional_price??p.price)*p.qty,0),[chosen]);
 const zone=zones.find(z=>z.id===zoneId);const deliveryFee=deliveryType==="delivery"&&zone?(zone.free_above!=null&&subtotal>=zone.free_above?0:zone.fee):0;const total=subtotal+deliveryFee;const demoMode=Boolean(merchant?.service_settings?.demo_mode&&merchant?.service_settings?.allow_demo_payment);
 function qty(id:string,delta:number){setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+delta)}))}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!user){setNotice("Entre na sua conta do PreçoCerto para continuar para o pagamento.");return}if(!chosen.length){setNotice("Adicione pelo menos um produto ao pedido.");return}if(deliveryType==="delivery"&&!zoneId){setNotice("Escolha a região de entrega.");return}setSubmitting(true);setNotice("");const fd=new FormData(e.currentTarget);const complement=String(fd.get("complement")||"").trim();const result=await createMarketplaceOrder({merchantId,deliveryType,deliveryZoneId:deliveryType==="delivery"?zoneId:null,deliveryAddress:deliveryType==="delivery"?{street:String(fd.get("street")||""),number:String(fd.get("number")||""),neighborhood:zone?.neighborhood||zone?.name||"",complement,reference:complement}:null,customerName:String(fd.get("name")||"").trim(),customerPhone:String(fd.get("phone")||"").trim(),customerEmail:String(user.email||"").trim(),items:chosen.map(p=>({merchant_product_id:p.id,quantity:p.qty}))});if(result.error||!result.data?.order_id){setNotice(result.error||"Não foi possível criar o pedido.");setSubmitting(false);return}const orderId=String(result.data.order_id);if(result.data.requires_review){setNotice(`Pedido #${result.data.order_number} enviado para análise. Nenhuma cobrança foi realizada.`);setTimeout(()=>window.location.assign("/meus-pedidos"),1200);return}if(demoMode){const demo=await completeDemoPayment(orderId);if(demo.error){setNotice(demo.error);setSubmitting(false);return}setNotice(`Pedido #${result.data.order_number} pago em modo demonstração. Nenhuma cobrança real foi realizada.`);setTimeout(()=>window.location.assign("/meus-pedidos"),1000);return}const pay=await startMercadoPagoCheckout(orderId);if(pay.url){window.location.assign(pay.url);return}setNotice(`Pedido #${result.data.order_number} criado. ${pay.error||"O pagamento online ainda não está disponível nesta loja."}`);setSubmitting(false)}
 if(loading)return <main className="storefront-state">Carregando loja…</main>;
 if(!merchant)return <main className="storefront-state"><Store size={42}/><h1>Loja indisponível</h1><a href="/">Voltar ao PreçoCerto</a></main>;
 const isDorinha=/dorinha/i.test(merchant.name);
 return <main className={`storefront-pro${isDorinha?" storefront-pro--author":""}`}>
  <header className="storefront-pro__top"><a href={isDorinha?"/dorinha-barroso":"/"} className="storefront-pro__back"><ArrowLeft/> {isDorinha?"Voltar à autora":"PreçoCerto"}</a><div className="storefront-pro__store"><Store/><span><strong>{merchant.name}</strong><small>{demoMode?"Ambiente de demonstração":"Compra segura"}</small></span></div><div className="storefront-pro__top-actions"><a href="/meus-pedidos">Meus pedidos</a><button type="button" className="storefront-pro__theme" onClick={()=>setTheme(t=>t==="dark"?"light":"dark")} aria-label={theme==="dark"?"Ativar modo claro":"Ativar modo escuro"}>{theme==="dark"?<Sun/>:<Moon/>}<span>{theme==="dark"?"Claro":"Escuro"}</span></button></div></header>
  {demoMode&&<div className="storefront-pro__demo">MODO DEMONSTRAÇÃO · nenhuma cobrança real será criada.</div>}
  <section className="storefront-pro__hero"><div className="storefront-pro__hero-bg" aria-hidden="true"/><div className="storefront-pro__hero-copy"><span className="storefront-pro__eyebrow">{isDorinha?"LIVRARIA DA AUTORA":"LOJA ONLINE"}</span><h1>{isDorinha?"Escolha sua próxima leitura.":merchant.name}</h1><p>{isDorinha?"Selecione os livros, informe apenas os dados essenciais e finalize no checkout protegido do Mercado Pago.":"Escolha seus produtos e finalize em poucos passos com pagamento seguro pelo Mercado Pago."}</p><div className="storefront-pro__hero-meta"><span><ShieldCheck/> Checkout protegido</span><span><QrCode/> Pix no Mercado Pago</span><span><CheckCircle2/> Valores validados antes do pagamento</span></div></div>{isDorinha&&<div className="storefront-pro__hero-art"><img src="/dorinha-author-portrait-v2.webp" alt="Dorinha Barroso"/><div><span>Compra direta</span><strong>Dorinha Barroso</strong><small>Literatura acreana</small></div></div>}</section>
  <div className="storefront-pro__layout"><section className="storefront-pro__catalog"><div className="storefront-pro__section-head"><div><span>CATÁLOGO</span><h2>{isDorinha?"Livros disponíveis":"Produtos disponíveis"}</h2></div><b>{products.length}</b></div><div className="storefront-pro__grid">{products.map(p=>{const price=p.promotional_price??p.price,q=cart[p.id]||0;return <article key={p.id} className={`storefront-pro__product${q?" is-selected":""}`}><div className="storefront-pro__image">{p.image_url?<img src={p.image_url} alt={p.product_name}/>:<ShoppingBag/>}</div><div className="storefront-pro__product-body"><strong>{p.product_name}</strong><span className="storefront-pro__price">{brl.format(price)}</span>{p.promotional_price!=null&&<small className="storefront-pro__old">{brl.format(p.price)}</small>}<div className="storefront-pro__qty"><button onClick={()=>qty(p.id,-1)} disabled={!q} aria-label={`Diminuir ${p.product_name}`}><Minus/></button><b>{q}</b><button onClick={()=>qty(p.id,1)} aria-label={`Adicionar ${p.product_name}`}><Plus/></button></div></div></article>})}{!products.length&&<div className="storefront-pro__empty">A loja ainda não liberou produtos para compra online.</div>}</div></section>
   <aside className="storefront-pro__checkout"><div className="storefront-pro__checkout-card"><div className="storefront-pro__checkout-head"><div><span>FINALIZAR COMPRA</span><h2>{chosen.length?`${chosen.length} item${chosen.length===1?"":"s"} no pedido`:"Seu pedido"}</h2></div><div className="storefront-pro__steps"><span>1</span><b>Dados</b><i/><span>2</span><b>Pagamento</b></div></div><div className="storefront-pro__items">{chosen.map(p=><div key={p.id}><span>{p.qty}× {p.product_name}</span><b>{brl.format((p.promotional_price??p.price)*p.qty)}</b></div>)}</div><div className="storefront-pro__delivery">{merchant.delivery_enabled&&<button onClick={()=>setDeliveryType("delivery")} className={deliveryType==="delivery"?"is-active":""}><Truck/> Entrega</button>}{merchant.pickup_enabled&&<button onClick={()=>setDeliveryType("pickup")} className={deliveryType==="pickup"?"is-active":""}><Store/> Retirada</button>}</div><form onSubmit={submit}>{deliveryType==="delivery"&&<><label>Região de entrega<select value={zoneId} onChange={e=>setZoneId(e.target.value)} required><option value="">Escolha sua região</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name} · {brl.format(z.fee)}</option>)}</select></label><div className="storefront-pro__two"><label>Rua<input name="street" required/></label><label>Número<input name="number" required/></label></div><label>Complemento ou referência <small>opcional</small><input name="complement"/></label></>}<div className="storefront-pro__two"><label>Seu nome<input name="name" required defaultValue={user?.user_metadata?.full_name||user?.user_metadata?.name||""}/></label><label>WhatsApp<input name="phone" required inputMode="tel"/></label></div><div className="storefront-pro__summary"><span>Produtos <b>{brl.format(subtotal)}</b></span>{deliveryType==="delivery"&&<span>Entrega <b>{zoneId?brl.format(deliveryFee):"—"}</b></span>}<strong>Total <b>{brl.format(total)}</b></strong></div>{notice&&<div className="storefront-pro__notice">{notice}</div>}<div className="storefront-pro__payment"><div><QrCode/></div><span><strong>Pagamento pelo Mercado Pago</strong><small>Na próxima tela você escolhe Pix ou outra forma disponível.</small></span><LockKeyhole/></div><button disabled={submitting||!chosen.length} className="storefront-pro__pay"><CreditCard/>{submitting?"Preparando pagamento…":demoMode?"Simular pagamento":"Ir para pagamento seguro"}</button><small className="storefront-pro__disclaimer"><CheckCircle2/> O valor e a disponibilidade são validados antes do checkout.</small></form></div></aside>
  </div>
 </main>
}
