import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeCheck, Building2, MapPin, Search, ShoppingBag, Store, Tag, Truck } from "lucide-react";
import { useParams } from "react-router-dom";
import { supabase } from "../lib/roles";

type Item={id:string;name:string;image_url?:string|null;category?:string|null;brand?:string|null;size?:string|null;unit?:string|null;price:number;previous_price?:number|null;promotional_price?:number|null;available:boolean;source:string;updated_at?:string|null};
type Profile={establishment:{id:string;slug:string|null;name:string;neighborhood:string|null;kind:string|null;brand_color:string|null;logo_url:string|null;short_description:string|null;is_verified:boolean;is_sponsored:boolean;partner_tier:string};merchant:null|{id:string;business_type:string;online_sales_enabled:boolean;delivery_enabled:boolean;pickup_enabled:boolean;phone:string|null;address:any;service_settings:any};catalog:Item[]};
const brl=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});

export function PublicEstablishmentCatalog(){
 const {identifier=""}=useParams();
 const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[category,setCategory]=useState("all");
 useEffect(()=>{void(async()=>{if(!supabase){setLoading(false);return}const {data}=await supabase.rpc("establishment_public_catalog",{_identifier:identifier});setProfile((data||null) as Profile|null);setLoading(false)})()},[identifier]);
 const categories=useMemo(()=>Array.from(new Set((profile?.catalog||[]).map(x=>x.category).filter(Boolean) as string[])).sort(),[profile]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return (profile?.catalog||[]).filter(x=>(!q||`${x.name} ${x.brand||""} ${x.category||""}`.toLowerCase().includes(q))&&(category==="all"||x.category===category))},[profile,query,category]);
 if(loading)return <main style={s.center}>Carregando catálogo…</main>;
 if(!profile)return <main style={s.center}><Store size={42}/><h1>Estabelecimento não encontrado</h1><a href="/estabelecimentos">Voltar aos estabelecimentos</a></main>;
 const e=profile.establishment,m=profile.merchant,online=Boolean(m?.online_sales_enabled),direct=Boolean(m?.service_settings?.direct_sales_enabled),author=m?.business_type==="books_author"||e.slug==="dorinha-barroso-livros";
 return <main style={s.page}>
  <style>{`@media(max-width:760px){.pc-cat-hero{grid-template-columns:1fr!important}.pc-cat-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.pc-cat-filters{grid-template-columns:1fr!important}}@media(max-width:520px){.pc-cat-grid{grid-template-columns:1fr!important}}`}</style>
  <header style={s.header}><a href="/estabelecimentos" style={s.back}><ArrowLeft size={16}/> Estabelecimentos</a><a href="/" style={s.brand}>PreçoCerto <small>Marketplace Local</small></a></header>
  <section style={{...s.hero,background:`linear-gradient(135deg,${e.brand_color||"#0c2d27"},#071a29)`}}><div style={s.heroInner} className="pc-cat-hero"><div><div style={s.badges}>{e.is_verified&&<span><BadgeCheck size={14}/> Verificado</span>}{e.is_sponsored&&<span><Tag size={14}/> Patrocinado</span>}{online&&<span><ShoppingBag size={14}/> Venda online</span>}{direct&&<span><ShoppingBag size={14}/> Venda direta</span>}</div><h1>{e.name}</h1><p>{e.short_description||"Explore os produtos e preços disponíveis neste estabelecimento pelo PreçoCerto."}</p><div style={s.meta}>{e.neighborhood&&<span><MapPin size={15}/>{e.neighborhood}</span>}{m?.delivery_enabled&&<span><Truck size={15}/>Entrega</span>}{m?.pickup_enabled&&<span><Building2 size={15}/>Retirada</span>}</div></div><div style={s.heroCard}><strong>{profile.catalog.length}</strong><span>itens no catálogo</span>{author?<a href="/autora/dorinha-barroso">Abrir espaço da autora</a>:online&&m?<a href={`/loja/${m.id}`}>Comprar online</a>:direct?<span>Venda direta disponível</span>:<span>Consulte e compare os preços</span>}</div></div></section>
  <section style={s.content}><div style={s.heading}><div><span style={s.kicker}>CATÁLOGO DO ESTABELECIMENTO</span><h2>Navegue antes de decidir onde comprar</h2><p>Os preços exibidos refletem os dados cadastrados ou capturados no PreçoCerto. Disponibilidade pode mudar.</p></div>{online&&m&&<a href={`/loja/${m.id}`} style={s.buyTop}><ShoppingBag size={17}/> Ir para compra online</a>}</div>
   <div style={s.filters} className="pc-cat-filters"><label style={s.search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar produto, marca ou categoria"/></label><select value={category} onChange={e=>setCategory(e.target.value)} style={s.select}><option value="all">Todas as categorias</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
   <div style={s.grid} className="pc-cat-grid">{filtered.map(item=>{const price=item.promotional_price??item.price;return <article key={item.id} style={s.card}><div style={s.imageBox}>{item.image_url?<img src={item.image_url} alt={item.name} style={s.image}/>:<ShoppingBag size={28}/>}</div><div style={s.body}>{item.category&&<span style={s.type}>{item.category}</span>}<h3>{item.name}</h3>{(item.brand||item.size||item.unit)&&<small>{[item.brand,item.size,item.unit].filter(Boolean).join(" · ")}</small>}<div style={s.price}>{brl.format(Number(price||0))}</div>{(item.promotional_price!=null||item.previous_price!=null)&&<small style={s.old}>{brl.format(Number(item.promotional_price!=null?item.price:item.previous_price||0))}</small>}<span style={s.source}>{item.source==="merchant"?"Catálogo do estabelecimento":"Preço monitorado pelo PreçoCerto"}</span></div></article>})}{!filtered.length&&<div style={s.empty}>Nenhum item encontrado com esses filtros.</div>}</div>
  </section>
 </main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f5f7f6",color:"#142019",fontFamily:"Inter,system-ui,sans-serif"},header:{height:66,padding:"0 clamp(16px,4vw,56px)",display:"flex",alignItems:"center",justifyContent:"space-between",background:"white",borderBottom:"1px solid #e3e8e5"},back:{display:"flex",alignItems:"center",gap:6,color:"inherit",textDecoration:"none",fontWeight:750,fontSize:13},brand:{fontWeight:950,color:"#123d2b",textDecoration:"none"},hero:{color:"white"},heroInner:{maxWidth:1240,margin:"0 auto",padding:"64px 24px",display:"grid",gridTemplateColumns:"minmax(0,1fr) 280px",gap:40,alignItems:"end"},badges:{display:"flex",gap:7,flexWrap:"wrap"},meta:{display:"flex",gap:14,flexWrap:"wrap",marginTop:20,opacity:.8},heroCard:{background:"rgba(255,255,255,.1)",border:"1px solid rgba(255,255,255,.14)",borderRadius:18,padding:22,display:"grid",gap:6},content:{maxWidth:1240,margin:"0 auto",padding:"54px 24px 80px"},heading:{display:"flex",justifyContent:"space-between",gap:24,alignItems:"end",marginBottom:22},kicker:{fontSize:10,fontWeight:900,letterSpacing:".14em",color:"#16864a"},buyTop:{display:"inline-flex",alignItems:"center",gap:7,background:"#173d2a",color:"white",padding:"12px 15px",borderRadius:10,textDecoration:"none",fontWeight:850},filters:{display:"grid",gridTemplateColumns:"minmax(280px,1fr) 230px",gap:10,marginBottom:18},search:{display:"flex",alignItems:"center",gap:8,background:"white",border:"1px solid #dce4df",borderRadius:12,padding:"0 13px"},select:{minHeight:48,border:"1px solid #dce4df",borderRadius:12,background:"white",padding:"0 12px"},grid:{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12},card:{background:"white",border:"1px solid #e2e7e4",borderRadius:15,overflow:"hidden"},imageBox:{height:150,display:"grid",placeItems:"center",background:"#f8faf8",color:"#839087"},image:{maxWidth:"92%",maxHeight:135,objectFit:"contain"},body:{padding:13},type:{fontSize:9,fontWeight:850,letterSpacing:".1em",color:"#708078",textTransform:"uppercase"},price:{fontSize:20,fontWeight:950,marginTop:12},old:{textDecoration:"line-through",color:"#87928c"},source:{display:"block",marginTop:10,fontSize:9,color:"#849087"},empty:{gridColumn:"1/-1",padding:50,textAlign:"center",background:"white",borderRadius:14},center:{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:10}};