import { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Heart, ImageOff, MapPin, Menu, Search, ShieldCheck, ShoppingBasket, Sparkles, Store, TrendingDown, X } from "lucide-react";
import { buildCatalog, type Product, type StoreRow } from "../data/catalog";
import { fetchCatalog } from "../data/remoteCatalog";
import { getStoreLogoUrl } from "../data/storeLogos";
import "./TrueHomepage.css";
import "./TrueHomepageInteractionProMax.css";
import "./TrueHomepageColorContrastProMax.css";
import "./TrueHomepageDensityProMax.css";

const seed = buildCatalog();
const money = (value:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const number = (value:number) => new Intl.NumberFormat("pt-BR").format(value);

function ProductImage({product}:{product:Product}) {
 const category=(product.category||"Produto").trim();
 return <div className="th-product__media">{product.image_url?<img src={product.image_url} alt={product.name} loading="lazy"/>:<div className="th-product__placeholder" aria-label={`Imagem indisponível para ${product.name}`}><span><ImageOff aria-hidden="true"/></span><strong>{category}</strong><small>Imagem em atualização</small></div>}</div>;
}

export function TrueHomepage(){
 const [products,setProducts]=useState<Product[]>(seed.products); const [stores,setStores]=useState<StoreRow[]>(seed.stores); const [metrics,setMetrics]=useState(seed.metrics); const [query,setQuery]=useState(""); const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{let active=true;fetchCatalog().then(r=>{if(active){setProducts(r.products);setStores(r.stores);setMetrics(r.metrics)}}).catch(()=>undefined);return()=>{active=false}},[]);
 const featured=useMemo(()=>[...products].filter(p=>Number.isFinite(p.minPrice)&&p.minPrice>0).sort((a,b)=>Math.max(0,b.maxPrice-b.minPrice)-Math.max(0,a.maxPrice-a.minPrice)||a.minPrice-b.minPrice).slice(0,4),[products]);
 const topStores=useMemo(()=>[...stores].sort((a,b)=>b.products-a.products).slice(0,4),[stores]);
 const submitSearch=(e:FormEvent)=>{e.preventDefault();const v=query.trim();window.location.href=v?`/buscar?q=${encodeURIComponent(v)}`:"/buscar"};
 return <div className="true-home">
  <header className="th-header"><div className="th-shell th-header__inner"><a className="th-brand" href="/" aria-label="PreçoCerto - início"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/><span>Feijó-AC</span></a><nav className="th-nav"><a href="/buscar">Comparar</a><a href="/cesta-basica">Cesta inteligente</a><a href="/estabelecimentos">Lojas</a></nav><div className="th-header__actions"><a className="th-login" href="/login">Entrar</a><a className="th-button th-button--brand th-header__cta" href="/buscar">Pesquisar preços</a><button className="th-menu" type="button" aria-label="Abrir menu" onClick={()=>setMenuOpen(true)}><Menu/></button></div></div></header>
  {menuOpen&&<div className="th-mobile-menu" role="dialog" aria-modal="true"><button type="button" aria-label="Fechar menu" onClick={()=>setMenuOpen(false)}><X/></button><a href="/buscar">Comparar preços</a><a href="/cesta-basica">Cesta inteligente</a><a href="/estabelecimentos">Estabelecimentos</a><a href="/lojista">Sou comerciante</a><a href="/login">Entrar</a></div>}
  <main>
   <section className="th-hero"><div className="th-hero__image"/><div className="th-hero__overlay"/><div className="th-shell th-hero__content"><div className="th-hero__copy"><div className="th-kicker"><MapPin/> Feijó • Acre <span/> comparação local</div><h1>Seu dinheiro vale mais quando você <strong>compara antes.</strong></h1><p>Encontre produtos, compare preços dos comércios de Feijó e descubra rapidamente onde comprar melhor.</p><form className="th-search" onSubmit={submitSearch}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque arroz, café, leite..." aria-label="Buscar produto"/><button type="submit">Comparar <ArrowRight/></button></form><div className="th-trust"><span><CheckCircle2/> preços locais</span><span><ShieldCheck/> comparação transparente</span><span><TrendingDown/> foco em economia</span></div></div><aside className="th-hero-card"><div className="th-hero-card__label"><Sparkles/> PreçoCerto agora</div><div className="th-hero-card__stats"><div><strong>{number(metrics.products)}</strong><span>produtos</span></div><div><strong>{number(metrics.stores)}</strong><span>lojas</span></div><div><strong>{number(metrics.prices)}</strong><span>preços</span></div></div><a href="/melhores-precos">Ver melhores preços <ArrowRight/></a></aside></div></section>
   <section className="th-quick"><div className="th-shell th-quick__grid"><a href="/buscar"><span><Search/></span><div><strong>Buscar produto</strong><small>Compare em segundos</small></div><ArrowRight/></a><a href="/cesta-basica"><span><ShoppingBasket/></span><div><strong>Montar cesta</strong><small>Planeje sua compra</small></div><ArrowRight/></a><a href="/estabelecimentos"><span><Store/></span><div><strong>Ver lojas</strong><small>Explore Feijó</small></div><ArrowRight/></a></div></section>
   <section className="th-section"><div className="th-shell"><div className="th-heading"><div><span>Economize agora</span><h2>Diferenças de preço que valem atenção.</h2><p>Produtos com oportunidades encontradas no catálogo atual.</p></div><a href="/melhores-precos">Ver todos <ArrowRight/></a></div><div className="th-products">{featured.map(p=>{const saving=Math.max(0,p.maxPrice-p.minPrice);return <article className="th-product" key={String(p.id)}><ProductImage product={p}/><div className="th-product__body"><div className="th-product__topline"><span>{p.category||"Produto"}</span><button type="button" aria-label={`Favoritar ${p.name}`}><Heart/></button></div><h3>{p.name}</h3><p>{p.establishment}</p><div className="th-product__price"><strong>{money(p.minPrice)}</strong>{saving>0&&<span>diferença de até {money(saving)}</span>}</div><a href={`/produto/${p.slug||p.id}`}>Comparar <ArrowRight/></a></div></article>})}</div></div></section>
   <section className="th-section th-discover"><div className="th-shell th-discover__grid"><div className="th-basket-mini"><span className="th-eyebrow">Cesta inteligente</span><h2>Uma compra inteira, não só um produto.</h2><p>Monte sua lista, informe seu orçamento e compare combinações para gastar melhor.</p><a className="th-button th-button--brand" href="/cesta-basica">Montar minha cesta <ArrowRight/></a></div><div className="th-stores-wrap"><div className="th-heading th-heading--compact"><div><span>Perto de você</span><h2>Comércios de Feijó.</h2></div><a href="/estabelecimentos">Ver todos <ArrowRight/></a></div><div className="th-stores">{topStores.map(s=>{const logo=getStoreLogoUrl(s.name);return <a className="th-store" href={`/estabelecimento/${s.slug||s.id}`} key={String(s.id)}><div className="th-store__logo" style={{background:s.color||"#e2e8f0"}}>{logo?<img src={logo} alt={`Logo ${s.name}`} loading="lazy"/>:<Store/>}</div><div><strong>{s.name}</strong><span>{s.neighborhood}</span><small>{number(s.products)} produtos</small></div><ArrowRight/></a>})}</div></div></div></section>
   <section className="th-merchant"><div className="th-shell th-merchant__inner"><div><span className="th-eyebrow">Para comerciantes</span><h2>Seu comércio onde o consumidor já procura preço.</h2><p>Mostre catálogo, ofertas e presença local dentro do PreçoCerto.</p></div><a className="th-button th-button--light" href="/lojista">Conhecer área do lojista <ArrowRight/></a></div></section>
  </main>
  <footer className="th-footer"><div className="th-shell th-footer__row"><div className="th-footer__brand"><img src="/logo-preco-certo-inversa.svg" alt="PreçoCerto"/><span>Feijó-AC</span></div><nav><a href="/buscar">Comparar</a><a href="/cesta-basica">Cesta</a><a href="/estabelecimentos">Lojas</a><a href="/lojista">Lojista</a><a href="/fale-conosco">Contato</a></nav><small>PreçoCerto • comparação local de preços</small></div></footer>
 </div>
}